### ISSUE TITLE
WebSocketMessageWriterStream is not flushed when writing async.

### ISSUE THREAD

**Issue by NimaAra** [vtortola/WebSocketListener#86] opened 2016-08-20 13:04 UTC
Given the following server:

```csharp
internal class Program
{
    private static void Main()
    {
        var server = StartServer();
        var cts = new CancellationTokenSource();
        var acceptTask = AcceptClientsAsync(server, cts.Token);

        Console.ReadLine();
        cts.Cancel();
        var stoppedInTime = acceptTask.Wait(1000);
        Console.WriteLine("Stopped in time: " + stoppedInTime.ToString());
        Console.ReadLine();
    }

    private static WebSocketListener StartServer()
    {
        var server = new WebSocketListener(new IPEndPoint(IPAddress.Loopback, 11123), new WebSocketListenerOptions());
        var standard = new WebSocketFactoryRfc6455(server);
        server.Standards.RegisterStandard(standard);
        server.Start();
        return server;
    }

    private static Task AcceptClientsAsync(WebSocketListener listener, CancellationToken cToken)
    {
        return Task.Factory.StartNew(async () =>
        {
            try
            {
                while (!cToken.IsCancellationRequested)
                {
                    var client = await listener.AcceptWebSocketAsync(cToken).ConfigureAwait(false);
                    if (client != null)
                    {
                        await Task.Run(() => HandleClientAsync(client, cToken), cToken).ConfigureAwait(false);
                    }
                }

                Console.WriteLine("Stopped accepting clients...");
            }
            catch (Exception ex)
            {
                // logging
            }
        }, cToken, TaskCreationOptions.LongRunning | TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
    }

    private static async Task HandleClientAsync(WebSocket client, CancellationToken cToken)
    {
        try
        {
            while (client.IsConnected && !cToken.IsCancellationRequested)
            {
                var msg = await client.ReadMessageAsync(cToken).ConfigureAwait(false);
                if (msg != null)
                {
                    // Read
                    switch (msg.MessageType)
                    {
                        case WebSocketMessageType.Text:
                            using (var reader = new StreamReader(msg, Encoding.UTF8))
                            {
                                var receivedText = await reader.ReadToEndAsync().ConfigureAwait(false);
                                Console.WriteLine("[Client] -> Text - " + receivedText);
                            }
                            break;
                        case WebSocketMessageType.Binary:
                            using (var memStream = new MemoryStream())
                            {
                                await msg.CopyToAsync(memStream).ConfigureAwait(false);
                                await msg.FlushAsync(cToken).ConfigureAwait(false);
                                var receivedBytes = memStream.ToArray();
                                Console.WriteLine("[Client] -> Bytes - " + receivedBytes);
                            }
                            break;
                        default:
                            throw new ArgumentOutOfRangeException(nameof(msg.MessageType), "Invalid message type");
                    }

                    // Writing byte[]
                    Console.WriteLine($"Writing Reply - [{Thread.CurrentThread.ManagedThreadId.ToString()}]");
                    var someBytes = Encoding.UTF8.GetBytes("[Server] -> Foo");
                    using (var writer = client.CreateMessageWriter(WebSocketMessageType.Binary))
                    {
                        await writer.WriteAsync(someBytes, 0, someBytes.Length, cToken);
                        await writer.FlushAsync(cToken);
                    }                    
                }
            }
        } catch (Exception aex)
        {
            Console.WriteLine("Error handling connection: " + aex.GetBaseException().Message);

            try
            {
                client.Close();
            } catch
            {
                /* ignored */
            }
        } finally
        {
            client.Dispose();
        }
    }
}
```

After receiving client's first message when we try to write a byte[] back using:

```csharp
// Writing byte[]
Console.WriteLine($"Writing Reply - [{Thread.CurrentThread.ManagedThreadId.ToString()}]");
var someBytes = Encoding.UTF8.GetBytes("[Server] -> Foo");
using (var writer = client.CreateMessageWriter(WebSocketMessageType.Binary))
{
    await writer.WriteAsync(someBytes, 0, someBytes.Length, cToken);
    await writer.FlushAsync(cToken);
}  
```

The stream is never flushed however if I remove the `FlushAsync` or change the `WriteAsync` to `Write` the issue goes away e.g the following two options work fine:

```csharp
using (var writer = client.CreateMessageWriter(WebSocketMessageType.Binary))
{
    await writer.WriteAsync(someBytes, 0, someBytes.Length, cToken).ConfigureAwait(false);    
}  
```

```csharp
using (var writer = client.CreateMessageWriter(WebSocketMessageType.Binary))
{
    await writer.Write(someBytes, 0, someBytes.Length);    
}  
```
It looks like `FlushAsync` is doing something it shouldn't.

FYI, I am using WebSocket4Net as the client:

```csharp
void Main()
{
    var wsUri = "ws://localhost:11123";
    var client = new WebSocket(wsUri, "", WebSocketVersion.Rfc6455);    
    client.Opened += (_, __) =>
    {
        var bytes = Encoding.UTF8.GetBytes("1st Hello");
        client.Send(bytes, 0, bytes.Length);
    };
    client.Closed += (_, __) => { };
    client.DataReceived += (_, __) =>
    {
        var bytes = Encoding.UTF8.GetBytes("2nd Hello");
        client.Send(bytes, 0, bytes.Length);
    };
    client.MessageReceived += (_, __) => { };
    client.Error += (_, __) => { };
    
    client.Open();    
    Console.ReadLine();   
}
```

Thank you

**Comment by vtortola** [comment] 2016-08-20 19:10
Hi, I cannot reproduce your issue using `ClientWebSocket`. I [modified your example](https://gist.github.com/vtortola/56a44818d2307eb12daf6b08ed8de31c) to run a client in another task sending messages each half second and all of them arrive to the client.

Also note there is something wrong in your code,  `Task.Factory.StartNew` do not understand `async` delegates. This is a common flaw.

**Comment by NimaAra** [comment] 2016-08-20 20:36
Why is it wrong? 
`Task.Factory.StartNew` in that context is valid as it is representing a `thread` responsible for accepting the clients. The task does not need to represent or understand the async work happening inside of it. 
In summary, [Stephen's](http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html) and [Toub's](https://blogs.msdn.microsoft.com/pfxteam/2011/10/24/task-run-vs-task-factory-startnew/) concerns do not apply here.

Anyhow, even with using `Task.Run()` the same problem happens.

Have you tried using a different client other than `ClientWebSocket` against your gist? You can easily copy/paste my client example into `LINQPad` and just reference WebSocket4Net via NuGet.

When I try to put manual delays in between, the client is able to receive messages.

```csharp
using (var writer = client.CreateMessageWriter(vtortola.WebSockets.WebSocketMessageType.Binary))
{
    await writer.WriteAsync(someBytes, 0, someBytes.Length, cToken);
    Thread.Sleep(1000);
    await writer.FlushAsync(cToken);
    Thread.Sleep(1000);
}
```
It looks like a deadlock issue to me.

**Comment by vtortola** [comment] 2016-08-21 00:53
It is wrong because when you do `var acceptTask = AcceptClientsAsync(server, cts.Token);` , that `acceptTask` finished in the moment its delegate hit `AcceptWebSocketAsync`, and since you are doing `var stoppedInTime = acceptTask.Wait(1000);` later on, it seems you have some expectation of that task having to finish, however it is already finished.

For example, this code:
```
static void Main(string[] args)
{
    Console.WriteLine(DateTime.Now.ToString("hh:mm:ss") + " Start");
    var task = Task.Factory.StartNew(async ()=>
    {
        Console.WriteLine(DateTime.Now.ToString("hh:mm:ss") + " Start of task.");
        await Task.Delay(2000).ConfigureAwait(false);
        Console.WriteLine(DateTime.Now.ToString("hh:mm:ss") + " End of task.");
    }, CancellationToken.None, TaskCreationOptions.LongRunning | TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
    task.Wait();
    Console.WriteLine(DateTime.Now.ToString("hh:mm:ss") + " End.");
    Console.ReadKey(true);
}

```

Prints:
```
10:11:19 Start
10:11:19 Start of task.
10:11:19 End.
10:11:21 End of task.
```

However if you replace `Task.Factory.StartNew` for `Task.Run` it prints :
```
10:13:27 Start
10:13:27 Start of task.
10:13:29 End of task.
10:13:29 End.
```

Another task problem is that you cannot do this: `await Task.Run(() => HandleClientAsync(client, cToken), cToken).ConfigureAwait(false);` , because then the logic of `AcceptClientsAsync` is blocked and is not accepting more clients concurrently.

Now, coming back to your issue, the problem is that the component you are using does not support [fragmentation](https://tools.ietf.org/html/rfc6455#section-5.4), **and what is that?** It is the ability of sending a message in multiple frames without specifying the total length of the message, in order to provide for example streaming; **and how is that related with this?** Well, this component flushes completely when `.Dispose` is called, but if you call to `.Flush` or `.FlushAsync` before that happening, a partial frame with the message so far is sent, and when you call `.Dispose` the remainder bytes in the buffer are sent, or if there is no remainder, a closing frame with 0 bytes is sent to finalize the message. So, if you never do a flush and the data you have in the message fits in the `WebSocket` object buffer, when you dispose the writer, a complete message in a single frame is sent; but! if you flush the message a partial frame will be sent, also if you hit the maximum buffer length, and when disposing, the message closing frame will be sent, even if it is 0 bytes. This is how I implemented the "stream interface" of this component, that allow you to work with variable length streams without having to materialize a complete `Byte[]` in memory.

And that is the reason why the Microsoft client works, and that one does not, because MS supports the complete specification.

**Comment by NimaAra** [comment] 2016-08-21 01:52
Once again in this context `Task.Factory` is the right choice in fact you show it quite well in your example:
```text
10:11:19 Start
10:11:19 Start of task.
10:11:19 End.
10:11:21 End of task.
```
This is exactly how I expect the application to behave. As I mentioned before, the long-running thread does not need to know about the inner tasks as it simply represents the execution period during which the server is _allowed_ to listen.

If you notice the following lines:

```csharp
var server = StartServer();
var cts = new CancellationTokenSource();
var acceptTask = AcceptClientsAsync(server, cts.Token);

Console.ReadLine();
cts.Cancel();
var stoppedInTime = acceptTask.Wait(1000);
Console.WriteLine("Stopped in time: " + stoppedInTime.ToString());
```

Passing `Console.ReadLine()` means the application should no longer listen therefore we tell the rest of the pipeline to stop (via `cts.Cancel()`) at that point I am willing to give a 1 second `grace` period before returning execution to the caller; In other words I do not wish nor care to wait for any of the inner tasks to finish awaiting or otherwise. You can think of this as a glorified `Thread.Abort()` minus all the nastiness.

With regards to the issue itself, thank you for the explanation I just tried another client and that one is behaving as expected. It is a shame that _Microsoft_'s client has an OS dependency which means I have to resort to less reliable clients. Any plans on implementing a complaint client yourself?

**Comment by vtortola** [comment] 2016-08-21 02:04
If that is what you expected I guess is OK :)

I am afraid I have no plans to implement a client, I am busy with other thing and being W8 released 3 years ago and now with .NET core in the lookout it does not feel like something interesting to do.

**Closed** 2016-08-21 11:06 UTC
