### ISSUE TITLE
Disconnection from server after few secons/minuts

### ISSUE THREAD

**Issue by warenbe** [vtortola/WebSocketListener#114] opened 2017-08-22 14:16 UTC
Hello
i'm using Websocketlistener in one of my project
my C# software is listening for connection, and have 2 threads : 
1 related to reading messages from client socket
1 related to sending messages in queue to client socket.

I have a javascript test page very very simple just displaying received messages from the server.
the test page connect (on localhost) successfully but after few minuts/seconds i have a disconnection with code 1001
On the server, when the problem occur, i have sock.ReadString() returning null.

On the server, i have ping option on BandwidthSaving mode, and ping every 20 seconds. timeout after 60 seconds. 
the problem occur sometimes after 10 seconds, sometimes after 5 minutes.
do you have any idea why ?

**Comment by warenbe** [comment] 2017-08-22 14:17
i forgot to say, the server is sending very very few messages right now. but any timeout should be avoided because of the ping right ?
or should i send every X seconds a null packet to help keeping the link open ?

**Comment by deniszykov** [comment] 2017-08-22 14:28
Can you provide message receiving code (short version). Which synchronization technique do you use to send messages?

**Comment by warenbe** [comment] 2017-08-22 14:39
Hello 
thank you for this answer
what do you mean by "message receiving code" ?

here is the code of the server (extract of the code) 

`
private void _read()
        {
            try
            {
                while (run)
                {
                    string msgContent = sock.ReadString();
                    if (msgContent != null)
                    {
                        dateDernierMessageRecu = DateTime.Now;
                        dataHandlerMethod?.Invoke(this, msgContent);
                    }
                    else
                    {
                        Close(true);
                    }
                }
            }
            catch (Exception ex)
            {
                if (run)
                {
                    Console.WriteLine("Exception " + ex.Message);
                    Close(false);
                }
            }
        }


private void _send()
        {
            try
            {
                while (run)
                {
                    string msg = "";
                    lock (locker)
                    {
                        if (messages.Count > 0)
                        {
                            msg = messages[0];
                            messages.RemoveAt(0);
                        }
                    }
                    if (msg != "")
                    {
                        sock.WriteString(msg);
                    }
                    else
                    {
                        //pause de 1 ms
                        Thread.Sleep(1);
                    }
                }
            }
            catch (Exception ex)
            {
                if (run)
                {
                    Console.WriteLine("Exception : " + ex.Message);
                }
            }
        }
`

these 2 methods are running in a loop in a séparate thread.

**Comment by deniszykov** [comment] 2017-08-22 14:49
I'm not sure that the API will work correctly in synchronous mode. You should try async version:

```
 static async Task EchoAsync(WebSocket ws)
{
            try
            {
                while (run)
                {
                    var msg = await ws.ReadStringAsync(CancellationToken.None).ConfigureAwait(false);
                    if (msg == null)
                        continue;
                    
                    // this method should not block execution for long
                    dataHandlerMethod?.Invoke(this, msgContent);
                }
            }
            catch (Exception aex)
            {
                try { ws.Close(); }
                catch { }
            }
            finally
            {
                ws.Dispose();
            }
}
```

**Comment by warenbe** [comment] 2017-08-22 14:56
Well 
i was using the async method before...
and i switched to the sync method because i also had disconnection problems.

i'm used to use threads and i'm not very very familiar with the async/await c# methods
i'll give it a try.

**Comment by warenbe** [comment] 2017-08-22 16:00
So, after trying with the async methods, i still have the issue :(

on the server i have this exception : 

> There is an ongoing message await from somewhere else. Only a single write is allowed at the time.

on the "ReadAsync" method

on the client i have a disconnection with error 1001

any other idea ?

Here is the new ReadAsync method and WriteAsync method
```
private async Task ReadAsync()
        {
            try
            {
                while (run)
                {
                    string msgContent = await sock.ReadStringAsync(CancellationToken.None).ConfigureAwait(false);
                    if (msgContent != null)
                    {
                        dateDernierMessageRecu = DateTime.Now;
                        AmiServ.log.Log(this.GetType().Name + "\t" + "Websocket " + sock.RemoteEndpoint.Address.ToString() + ":" + sock.LocalEndpoint.Port + " (" + Encoding.UTF8.GetByteCount(msgContent) + " B) >> " + msgContent, LOGGER_LEVEL.DEBUG);
                        OnWebsocketClientMessage?.Invoke(this, msgContent);
                    }
                    else
                    {
                        continue;
                    }
                }
                //déconnexion normale
                Close(true);
            }
            catch (Exception ex)
            {
                if (run)
                {
                    AmiServ.log.Log(this.GetType().Name + "\t" + "Websocket " + sock.RemoteEndpoint.Address.ToString() + ":" + sock.LocalEndpoint.Port + " Echec de lecture. " + ex.GetBaseException().Message, LOGGER_LEVEL.WARN);
                    Close(false);
                }
            }
        }

private async Task SendAsync()
        {
            try
            {
                while (run)
                {
                    string msg = "";
                    lock (locker)
                    {
                        if (messages.Count > 0)
                        {
                            msg = messages[0];
                            messages.RemoveAt(0);
                        }
                    }
                    if (msg != "")
                    {
                        AmiServ.log.Log(this.GetType().Name + "\t" + sock.RemoteEndpoint.Address.ToString() + ":" + sock.LocalEndpoint.Port + "(" + Encoding.UTF8.GetByteCount(msg) + " B) << " + msg, LOGGER_LEVEL.DEBUG);
                        await sock.WriteStringAsync(msg, CancellationToken.None);
                    }
                    else
                    {
                        //pause de 1 ms
                        Thread.Sleep(1);
                    }
                }
            }
            catch (Exception ex)
            {
                if (run)
                {
                    AmiServ.log.Log(this.GetType().Name + "\t" + "Websocket " + sock.RemoteEndpoint.Address.ToString() + ":" + sock.LocalEndpoint.Port + " Echec d'écriture. " + ex.GetBaseException().Message, LOGGER_LEVEL.WARN);
                }
            }
        }
```

And i call these methods using : 

```
            Task.Run(() => ReadAsync());
            Task.Run(() => SendAsync());
```

directly in the constructor of the class

**Comment by deniszykov** [comment] 2017-08-22 16:06
This method ```OnWebsocketClientMessage?.Invoke(this, msgContent)``` is not blocking execution?
It is better to queue incoming message and don't block receive task.

```
private Queue<KeyValuePair<MyClass, string>> queue;

// ...
 
if (msgContent != null)
{
      dateDernierMessageRecu = DateTime.Now;
      AmiServ.log.Log(...);
      lock(queue)
             queue.Enqeue(new KeyValuePair<MyClass, string>(this, msgContent));
}
else
{
      break; // connection is closed
 }
```

**Comment by warenbe** [comment] 2017-08-22 16:08
Here is the execution of this event : 

```
private void Client_OnWebsocketClientMessage(object sender, string msg)
        {
            WebsocketClient client = (WebsocketClient)sender;
            SocketCommand cmd = null;
            try
            {
                cmd = JsonConvert.DeserializeObject<SocketCommand>(msg);
            }
            catch (Exception ex)
            {
                AmiServ.log.Log("SocketMessage\t" + "Echec de décodage commande websocket : " + ex.Message, LOGGER_LEVEL.ERROR);
            }
            MessageDispatcherAsync(client, cmd);
        }

        private async void MessageDispatcherAsync(WebsocketClient client, SocketCommand cmd)
        {
            await Task.Run(() =>
            {
                if (cmd != null)
                {
                    switch (cmd.Command.ToLower())
                    {
                        case "ping":
                            PingCommand(client, cmd);
                            break;
                        default:
                            UnknownCommand(client, cmd);
                            break;
                    }
                }
            });
        }
```

so it should not block.
currently it does not do lot of things ;)

the problem is : i got the disconnection without any message sent from the server/client
so it cannot be because this method blocked, because we never get there :(

i'll change to queue the incoming messages, it's a good idea. but it's not the problem i think.

**Comment by deniszykov** [comment] 2017-08-22 16:18
> so it should not block.
Yes, it doesn't seems to block execution.

You get ```There is an ongoing message await from somewhere else. Only a single write is allowed at the time.``` error because after receiving null message should stop receiving and close socket. But in you loop you  ``` continue;```, instead of ```break```.

As i see there is two reasons for close code 1001:

- Client send close frame (closed from client)
- WebSocket.Close is called

Ping related disconnection is ```WebSocketCloseReasons.GoingAway```. Are you sure client is not closing connection? You can watch WS frames with Chrome developer tools.

**Comment by warenbe** [comment] 2017-08-22 16:19
I'm using Firefox, and on firefox i get an error in the console saying that the socket was closed.
I'll check the frames with chrome.

**Comment by warenbe** [comment] 2017-08-22 16:30
So
i connect
then wait... 
and suddenly : socket disconnected (1001 : on client side)
and i cannot see any frame :(
![capture](https://user-images.githubusercontent.com/25795188/29576382-e406b492-8767-11e7-9fec-2c83780fa6ed.PNG)

**Comment by deniszykov** [comment] 2017-08-22 16:37
Can you set breakpoint(or log) on Close() method, and make sure WebSocket is not disposed on the server.

**Comment by deniszykov** [comment] 2017-08-22 16:38
Also you can try my fork of this [package](https://github.com/deniszykov/WebSocketListener). API is same.

**Comment by warenbe** [comment] 2017-08-22 16:45
Yes sure i can put a breakpoint. 
the socket is not disposed.
apparently , on the client side, if i put a "setInterval" which send a 1 Byte packet every seconds, i don't have any disconnection... not sure because sometimes i get disconnected after minuts, sometimes after seconds...

i'll try your fork. if it's the same api it'll be easy to change.

**Comment by warenbe** [comment] 2017-08-22 17:02
Tried your package
installed with nuget
i'm stuck with options.Standards.RegisterRfc6455 not existing.

**Comment by deniszykov** [comment] 2017-08-22 17:15
it is in vtortola.WebSockets.Rfc6455. You should add ```using vtortola.WebSockets.Rfc6455```. Sorry not exactly same, with small changes.

**Comment by warenbe** [comment] 2017-08-22 17:18
dont excuse yourself... i relied on vs intellisense to tells me wichs namespace to use, and did not search for the solution. i'm tired, it explain this.

there are few change also. i'm changing few things and test it soon.

**Comment by warenbe** [comment] 2017-08-22 17:27
mmhhh. it's been already 4:40 running without disconnect. maybe your package has a fix...
OK it's late and i need to go home. 
i'll use your package (wich seems to be updated, Val seems to not update anymore this one.

i like his project btw because it's simple to use. i don't need very complicated websocket server, my app is just sending information to clients and receive sometimes messages...

i'll tell you on your project if i get problems.
thanks for helping.

**Comment by deniszykov** [comment] 2017-08-22 17:29
You are welcome. You can post found issues [here](https://github.com/deniszykov/WebSocketListener/issues).

**Comment by vtortola** [comment] 2017-08-22 21:44
Hi! I am not adding new things to this project anymore but I am interested in bugs :) 

Do you think you could pass me a small program similar to yours that reproduces the problem? 

@deniszykov  thanks for the support.

**Comment by warenbe** [comment] 2017-08-23 07:03
mmhhhh i made lot of modifications since i moved to @deniszykov fork.
so this morning i told myselft "i'll send yesterday backup"... to realize that i have no backup since 3 weeks because of a problem with my backup HDD !!

tsssss.

let me check if i can find another backup to send you something.

**Comment by warenbe** [comment] 2017-08-23 07:33
ok i found something... 
i took an old code from another project.
and i tried the same webpage and did not get any problem...
and then i realized that i was in "PintModes.Latency" on this project, and BandwithSaving on the other

so i tried moving from Latency to BandwithSaving on the old project and the problem appeared.
so it seems to be related to the ping mode in bandwith saving...

**Comment by vtortola** [comment] 2017-08-23 15:17
Thanks! I found the issue and fixed it. Cheers.

**Comment by warenbe** [comment] 2017-08-23 15:32
Great, maybe you should share the fix with @deniszykov  in case he has the same problem. 
i still have some problem of disconnection, and very slow coms, with denis fork, but i think this is because of my lack of knowledge with async/await methods....

**Comment by deniszykov** [comment] 2017-08-23 15:55
I have different implementation of Ping strategy so @vtortola fix doesn't apply to my fork. But i made a tests and found that default ```WebSocketListenerOptions.PingTimeout``` is set to quite small value "5 seconds"  try to change it to "10 seconds". 

Also you could try to set ```WebSocketListenerOptions.PingMode = PingMode.Manual,``` and check if problem persists.

>, and very slow coms
Can you provide more details. Thanks.

**Comment by warenbe** [comment] 2017-08-23 16:04
Well 5 seconds for a timeout does not seems to be small for me, all my test are made with loopback address.
Manuel means i have to launch the ping method sometimes. this is a requierement if i'm not wrong for websocket no ?

now i have 2 problems
i made a very ugly webpage to check if i can open multiple sockets. every time i click, a new socket is created. that's all. and if i click more than 1 time per second (approx), starting from the 5th socket, i have a 2/3 second delay between each socket connection. 
i can't find why.
if i click every 2 seconds on the button, the connection of the new socket is OK. attached a zip
[test.zip](https://github.com/vtortola/WebSocketListener/files/1246122/test.zip)


with the test page.

**Comment by deniszykov** [comment] 2017-08-23 16:57
>if i click every 2 seconds on the button, the connection of the new socket is OK. attached a zip with the test page.
This is browser related stuff. Test do 10k connections in 2 seconds(on my laptop), Chrome has no delay then connecting WS, but Firefox do 2-3 secs delay if you spam WS connections.

Thanks for test page. I found bug related to PingMode.BandwidthSaving. It cause random disconnection due wrong timeout logic. I will continue to test and will enroll fresh version soon.
>Well 5 seconds for a timeout does not seems to be small for me,
Ping frames are interleaved with data frames, if you start sending huge data frames whole connection could timeout due ping frame delay.

**Comment by vtortola** [comment] 2017-08-23 17:16
Hi, I rolled out a new package with the fix: https://www.nuget.org/packages/vtortola.WebSocketListener/2.2.3 

There was a funny thing going on because intervals were too tight, and `Task.Delay` not exact, so an offset was being accumulated and causing the disconnection.

Let me know if it works for you. @deniszykov I saw your implementation and it was different, so it may be unrelated to yours.

**Comment by warenbe** [comment] 2017-08-24 06:54
Hello.
@deniszykov  ok for the ping in understand now. effectively with a ping timeout at 20s, no more disconnection.
i'll also try a c# connection to exclude any problems related to FF or chrome. 

@vtortola : i will try it, i use your package in another older project suffering disconnections also. maybe it's related, i still dunno because the customer also have some network problems...

**Closed** 2017-08-25 08:33 UTC
