### ISSUE TITLE
Improper Interpretation of payload length

### ISSUE THREAD

**Issue by gtabmx** [vtortola/WebSocketListener#28] opened 2015-08-07 19:32 UTC
The TryParse in the WebSocketFrameHeader class uses ToInt16 and ToInt64 rather than treating the payload lengths as unsigned ints (as required by the rfc6455 spec), which causes issues in certain cases (negative payload lengths), which is critical. Lines 98 and 107.

**Comment by vtortola** [comment] 2015-08-07 19:55
Interesting. The problem is that unsigned integers are not CLS compliant. Can you explain the issue with negative payload lengths?

**Comment by gtabmx** [comment] 2015-08-07 20:10
https://tools.ietf.org/html/rfc6455 - Page 29.

In condition 2, where payload data is 126, if next 2 bytes are interpreted as an int, then if your payload is greater than 32767 in length (0x7FFF), then your contentLength will be rolled over into negative territory, breaking the rest of the implementation.

In condition 3, where payload data is 127, if next 8 bytes are interpreted as an int, then if your payload is greater than 9.223372e+18 in length (0x7FFFFFFFFFFFFFFF), then your contentLength will be rolled over into negative territory, breaking the rest of the implementation.

Clearly, no sane person would expect to be bothered by condition 3, but for condition 2, any message of size 32768 (0x7FFF) to I believe 65536 (0x10000) would result in an unfavourable situation.

**Comment by vtortola** [comment] 2015-08-07 20:29
Great. I won't have a laptop handy until Monday. I will try to reproduce these situations in th unit tests about header parsing. Thanks.

**Comment by gtabmx** [comment] 2015-08-10 17:58
Also, as I understand, for CLS compliance, only public members must be signed, whereas private and internal members can be unsigned.

**Comment by vtortola** [comment] 2015-08-10 19:22
That is right. I have done the pertinent changes in the changeset : https://github.com/vtortola/WebSocketListener/commit/f0a2cc2e74324b3fa0157e925cd3c7ab63848d93

Let me know your thoughts. And thanks for taking the time in reporting this.

**Comment by gtabmx** [comment] 2015-08-11 19:44
Great, so receiving in all cases of the above case 2 works well (from sizes 32768 (0x7FFF) to I believe 65535 (0xFFFF)) however, you need to make the same changes when you send and build your frame headers. As is stands, as message being sent that is between 32768 (0x7FFF) and 65535 (0xFFFF) in content length will once again cause a critical error in generating an incorrect frame header.

I believe this is because of your use of Int16.MaxValue rather than UInt16.MaxValue, and other uses of Int16 rather than UInt16 in your code. As for very large messages (Int64.MaxValue < x < UInt64.MaxValue) your library will simply throw an exception and refuse to send it.

**Comment by vtortola** [comment] 2015-08-11 23:01
Right, I just came from holidays so bear with me :)

I fixed the header creation as well: https://github.com/vtortola/WebSocketListener/commit/8c9361d9af8a8f603a98d6c9f9246eb3a3a870b0

(some changes to fix the CLS compliant thing have been added later)

There is no need to throw an exception since the creation helper only allows Int64.

**Comment by vtortola** [comment] 2015-08-19 22:29
This is fixed in the latest version : https://www.nuget.org/packages/vtortola.WebSocketListener/2.1.9

Cheers.

**Closed by vtortola** 2015-08-19 22:29 UTC
